### ISSUE TITLE
Unable to install (pyBigWig wheel error)

### ISSUE THREAD

**Issue by tahirasma** [liguowang/CrossMap#19]

**Comment by liguowang** [comment]
Hi,
Sorry I cannot figure out why the installation of pyBigWig failed. Could you manually install pyBigWig before installing CrossMap?

**Comment by ManavalanG** [comment]
Faced similar issue installing it using pip in conda, and installing pybigwig resolved it. Here is the conda env yaml I used:

```yaml
name: crossmap

channels:
- bioconda
- conda-forge

dependencies:
- python=3.7
- pybigwig
- pip
- pip:
    - CrossMap==0.5.2
```

Note: Can't fully remember (it's been a while) but I think above env didn't work when I tried it with `python=3.8`.
